name: Update Docker Hub Description
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
jobs:
  dockerhub-description:
    name: Update Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: gameservermanagers/linuxgsm
          short-description: ${{ github.event.repository.description }}
